config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  root 'tasks#index'

  resources :users
  resources :tasks do
    member do
      put :start
      put :finish
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can [:read, :update, :destroy], User, id: user.id
      can :manage, Task
      can :read, :all
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/task.rb
class Task < ActiveRecord::Base
  STATES = %w(new started finished)

  belongs_to :user
  mount_uploaders :attachments, AttachmentUploader

  validates :name, presence: true
  validates :state, presence: true, inclusion: { in: STATES }

  include AASM

  aasm column: :state do
    state :new, initial: true
    state :started
    state :finished

    event :start do
      transitions from: :new, to: :started
    end

    event :finish do
      transitions from: [:new, :started], to: :finished
    end
  end

  def started?
    state.eql?("started")
  end

  def finished?
    state.eql?("finished")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tasks
  
  validates :password_confirmation, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    render(:file => File.join(Rails.root, 'public/403.html'), :status => 403, :layout => false)
  end

  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :start, :finish]
  load_and_authorize_resource

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
    @attachments = @task.attachments
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def start
    redirect_to @task if @task.start && @task.save!
  end

  def finish
    redirect_to @task if @task.finish && @task.save!
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :state, :user_id, {attachments: []})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path, http_method=nil)
    class_name = current_page?(link_path) ? 'active' : ''

    content_tag(:li, class: class_name) do
      if http_method
        link_to(link_text, link_path, method: http_method)
      else
        link_to(link_text, link_path)
      end
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def assigned_user(user)
    if user.present?
      user.full_name
    else
      t('form.not_assigned')
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('application.title') %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= render partial: 'shared/nav_bar' %>

<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>

<%= render partial: 'shared/footer' %>
</body>
</html>

app/views/partials/task/_attachments.erb
<% @attachments.each do |attachment| %>
  <ul>
    <li>
      <%= attachment.filename %>
    </li>
  </ul>
<% end %>
<br>

app/views/partials/task/_current_state.erb
<div class="col-sm-6 col-md-4 col-md-offset-4">
  <div class="field form-group">
    <%= label_tag :current_state %> <br>
    <h3><%= @task.state %></h3><br>
    <%= render partial: 'partials/task/links' unless @task.finished? %>
  </div>
</div>

app/views/partials/task/_links.erb
<%= link_to t('tasks.links.start'), start_task_path(@task), method: :put unless @task.started? %><br>
<%= link_to t('tasks.links.finish'), finish_task_path(@task) , method: :put %>

app/views/shared/_footer.erb
<footer class="footer">
  <small>
    <a href="https://github.com/jitscar/task_manager_demo"><%= t('application.title') %></a>
    <% t('application.footer.author') %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t('application.footer.contact'), "https://github.com/jitscar" %></li>
    </ul>
  </nav>
</footer>

app/views/shared/_nav_bar.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to t('application.title'), root_path, id: "logo", class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= nav_link t('application.nav_bar.home'), root_path if user_signed_in? %>

        <% if user_signed_in? %>
          <%= nav_link t('application.nav_bar.edit_profile'), edit_user_registration_path %>
          <%= nav_link t('application.nav_bar.logout'), destroy_user_session_path, :delete %>
        <% else %>
          <%= nav_link t('application.nav_bar.login'), new_user_session_path %>
          <%= nav_link t('application.nav_bar.register'), new_user_registration_path %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/tasks/_form.html.erb
<div class="col-sm-6 col-md-4 col-md-offset-4">
  <%= form_for(@task) do |f| %>
    <% if @task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="field form-group">
      <%= f.label :user %><br>
      <%= collection_select(:task, :user_id, User.all, :id, :full_name, {prompt: true}, {class: "form-control"}) %>
    </div>
    <div class="field form-group">
      <%= f.label :attachments %><br>
      <%= render partial: 'partials/task/attachments' if @attachments %>
      <%= f.file_field :attachments, multiple: true %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/tasks/edit.html.erb
<h1><%= t('tasks.edit.title') %></h1>

<%= render partial: 'partials/task/current_state' %>
<%= render 'form' %>

<%= link_to t('actions.show'), @task %> |
<%= link_to t('actions.back'), tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('tasks.index.title') %></h1>

<table class="table">
  <thead>
    <tr>
      <th><%= t('tasks.labels.name') %></th>
      <th><%= t('tasks.labels.description') %></th>
      <th><%= t('tasks.labels.state') %></th>
      <th><%= t('tasks.labels.user') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.state %></td>
        <td><%= assigned_user(task.user) %></td>
        <td><%= link_to t('actions.show'), task %></td>
        <td><%= link_to t('actions.edit'), edit_task_path(task) %></td>
        <td><%= link_to t('actions.destroy'), task, method: :delete, data: { confirm: t('actions.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('tasks.links.new'), new_task_path %>

app/views/tasks/new.html.erb
<h1><%= t('tasks.new.title') %></h1>

<%= render 'form' %>

<%= link_to t('actions.back'), tasks_path %>

app/views/tasks/show.html.erb
<p>
  <strong><%= t('tasks.labels.name') %>:</strong>
  <%= @task.name %>
</p>

<p>
  <strong><%= t('tasks.labels.description') %>:</strong>
  <%= @task.description %>
</p>

<p>
  <strong><%= t('tasks.labels.state') %>:</strong>
  <%= @task.state %>
</p>

<p>
  <strong><%= t('tasks.labels.user') %>:</strong>
  <%= assigned_user(@task.user) %>
</p>

<%= link_to t('actions.edit'), edit_task_path(@task) %> |
<%= link_to t('actions.back'), tasks_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1><%= t('users.edit.title') %></h1>

<%= render 'form' %>

<%= link_to t('actions.show'), @user %> |
<%= link_to t('actions.back'), users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t('users.index.title') %></h1>

<table class="table">
  <thead>
    <tr>
      <th><%= t('users.labels.email') %></th>
      <th><%= t('users.labels.password') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to t('actions.show'), user %></td>
        <td><%= link_to t('actions.edit'), edit_user_path(user) %></td>
        <td><%= link_to t('actions.destroy'), user, method: :delete, data: { confirm: t('actions.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('users.links.new'), new_user_path %>

app/views/users/new.html.erb
<h1><%= t('users.new.title') %></h1>

<%= render 'form' %>

<%= link_to t('actions.back'), users_path %>

app/views/users/show.html.erb
<p>
  <strong><%= t('users.labels.email') %>:</strong>
  <%= @user.email %>
</p>

<p>
  <strong><%= t('users.labels.password') %>:</strong>
  <%= @user.password %>
</p>

<%= link_to t('actions.edit'), edit_user_path(@user) %> |
<%= link_to t('actions.back'), users_path %>